#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <sys/wait.h>
#include <unistd.h>
#include <string.h>

int main (int argc, char *argv[]) {
    printf("Main process ID: %d\n", (int) getpid());
    int rc = fork();
    if (rc < 0) {
        printf("Error: fork() failed\n");
        exit(EXIT_FAILURE);
    }
    else if (rc == 0) {
        // redirect the output from the standard output to p4
        close(STDOUT_FILENO); 
        open("./p4.output", O_CREAT|O_WRONLY|O_TRUNC, S_IRWXU);

        char *args[3];
        args[0] = strdup("echo");
        args[1] = strdup("This was generated by p4");
        args[2] = NULL;
        execvp(args[0], args);            
    }
    else {
        wait(NULL);
    }
    return 0;
}
